shell fish

font_family      CaskaydiaCove NFM Bold
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 14
include ./font-nerd-symbols.conf
include ./rose-pine.conf
confirm_os_window_close -1




