preload = /home/arya/.config/arya/wallpapers/macos_sonoma.jpg

wallpaper = DP-3,/home/arya/.config/arya/wallpapers/macos_sonoma.jpg
wallpaper = HDMI-A-1,/home/arya/.config/arya/wallpapers/macos_sonoma.jpg
wallpaper = DP-1,/home/arya/.config/arya/wallpapers/macos_sonoma.jpg


preload = /home/arya/.config/arya/wallpapers/anime_landscape.png

wallpaper = DP-3,/home/arya/.config/arya/wallpapers/anime_landscape.png
wallpaper = HDMI-A-1,/home/arya/.config/arya/wallpapers/anime_landscape.png
wallpaper = DP-1,/home/arya/.config/arya/wallpapers/anime_landscape.png

